import { Project } from '../types';

export interface ParsedBlueprintResult {
  project: Project | null;
  rawText: string;
  sheetNumber?: string;
  sheetTitle?: string;
  revision?: string;
  discipline?: string;
  scannedAt: string;
  sourceUrl?: string;
  isRecognized: boolean;
  confidenceMessage: string;
}

/**
 * Parses scanned QR text from a physical blueprint drawing.
 * Handles URLs, JSON tokens, URI schemes (e.g. FIZA-BIM://...), and direct project IDs.
 */
export function parseBlueprintQR(rawText: string, projects: Project[]): ParsedBlueprintResult {
  const trimmed = rawText.trim();
  const scannedAt = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });

  // 1. Try parsing JSON payload (e.g. generated by title-block stamps)
  if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
    try {
      const parsed = JSON.parse(trimmed);
      const targetId = parsed.projectId || parsed.id;
      const targetSlug = parsed.slug;
      const found = projects.find(p => p.id === targetId || p.slug === targetSlug || p.id === targetSlug);

      if (found) {
        return {
          project: found,
          rawText: trimmed,
          sheetNumber: parsed.sheetNumber || parsed.sheet || 'A-101',
          sheetTitle: parsed.sheetTitle || 'ARCHITECTURAL GENERAL ARRANGEMENT',
          revision: parsed.revision || parsed.rev || 'REV-01',
          discipline: parsed.discipline || 'Architecture & BIM',
          scannedAt,
          isRecognized: true,
          confidenceMessage: 'Exact match verified from digital CAD title block schema.'
        };
      }
    } catch {
      // Continue to next parsers
    }
  }

  // 2. Try URL parsing (e.g., https://domain.com/?project=proj-1 or /project/proj-1)
  try {
    if (trimmed.startsWith('http://') || trimmed.startsWith('https://') || trimmed.includes('?project=') || trimmed.includes('/project/')) {
      let urlObj: URL | null = null;
      try {
        urlObj = new URL(trimmed);
      } catch {
        // May be a relative or partial URL
        if (trimmed.startsWith('/')) {
          urlObj = new URL('https://fizahayat.com' + trimmed);
        }
      }

      if (urlObj) {
        const queryProj = urlObj.searchParams.get('project') || urlObj.searchParams.get('projectId') || urlObj.searchParams.get('id');
        const sheetParam = urlObj.searchParams.get('sheet') || urlObj.searchParams.get('sheetNumber');
        const revParam = urlObj.searchParams.get('rev') || urlObj.searchParams.get('revision');

        if (queryProj) {
          const found = projects.find(p => p.id === queryProj || p.slug === queryProj);
          if (found) {
            return {
              project: found,
              rawText: trimmed,
              sheetNumber: sheetParam || 'A-101',
              sheetTitle: 'SITE & ELEVATION BLUEPRINT',
              revision: revParam || 'REV-02',
              discipline: 'Architectural / BIM',
              scannedAt,
              sourceUrl: trimmed,
              isRecognized: true,
              confidenceMessage: 'Verified from web project link embedded in physical drawing.'
            };
          }
        }

        // Check path like /project/proj-1
        const pathParts = urlObj.pathname.split('/').filter(Boolean);
        const projectIndex = pathParts.findIndex(p => p === 'project' || p === 'projects');
        if (projectIndex !== -1 && pathParts[projectIndex + 1]) {
          const candidate = pathParts[projectIndex + 1];
          const found = projects.find(p => p.id === candidate || p.slug === candidate);
          if (found) {
            return {
              project: found,
              rawText: trimmed,
              sheetNumber: 'A-101',
              sheetTitle: 'CONSTRUCTION DRAWING SHEET',
              revision: 'REV-01',
              discipline: 'Architectural',
              scannedAt,
              sourceUrl: trimmed,
              isRecognized: true,
              confidenceMessage: 'Verified from drawing portal URL.'
            };
          }
        }
      }
    }
  } catch {
    // Continue
  }

  // 3. Try custom blueprint URI schemes (e.g. FIZA-BIM://project/proj-1?sheet=A-101 or BLUEPRINT:proj-1:A101)
  if (trimmed.toUpperCase().includes('FIZA-BIM:') || trimmed.toUpperCase().includes('BLUEPRINT:')) {
    const tokens = trimmed.split(/[:/?&=]+/);
    for (const token of tokens) {
      const found = projects.find(p => p.id.toLowerCase() === token.toLowerCase() || p.slug.toLowerCase() === token.toLowerCase());
      if (found) {
        return {
          project: found,
          rawText: trimmed,
          sheetNumber: 'A-201',
          sheetTitle: 'STRUCTURAL STEEL & CONCRETE DETAILS',
          revision: 'REV-03 (APPROVED)',
          discipline: 'Structural & BIM',
          scannedAt,
          isRecognized: true,
          confidenceMessage: 'Verified from BIM physical stamp protocol.'
        };
      }
    }
  }

  // 4. Try direct Project ID or Slug match (e.g. "proj-1", "obsidian-glass-villa")
  const directMatch = projects.find(p => 
    p.id.toLowerCase() === trimmed.toLowerCase() ||
    p.slug.toLowerCase() === trimmed.toLowerCase() ||
    p.id.toLowerCase().replace(/[^a-z0-9]/g, '') === trimmed.toLowerCase().replace(/[^a-z0-9]/g, '')
  );

  if (directMatch) {
    return {
      project: directMatch,
      rawText: trimmed,
      sheetNumber: 'A-101',
      sheetTitle: 'ARCHITECTURAL MASTER PLAN',
      revision: 'REV-01',
      discipline: 'General Architectural',
      scannedAt,
      isRecognized: true,
      confidenceMessage: 'Direct project code matched in enterprise database.'
    };
  }

  // 5. Try fuzzy title search (e.g. "Obsidian Glass Villa")
  const lowerTrimmed = trimmed.toLowerCase();
  const fuzzyMatch = projects.find(p => 
    lowerTrimmed.length > 4 && (
      p.title.toLowerCase().includes(lowerTrimmed) ||
      lowerTrimmed.includes(p.title.toLowerCase())
    )
  );

  if (fuzzyMatch) {
    return {
      project: fuzzyMatch,
      rawText: trimmed,
      sheetNumber: 'A-101',
      sheetTitle: 'SCHEMATIC DESIGN SHEET',
      revision: 'REV-01',
      discipline: 'Architectural Design',
      scannedAt,
      isRecognized: true,
      confidenceMessage: 'Matched project title inscribed in blueprint text.'
    };
  }

  // No match found
  return {
    project: null,
    rawText: trimmed,
    scannedAt,
    isRecognized: false,
    confidenceMessage: 'Scanned QR code is valid, but does not correspond to an active project in the portfolio.'
  };
}

/**
 * Creates standardized QR data string for blueprint title block stamping.
 */
export function generateBlueprintQRPayload(project: Project, sheet: string = 'A-101', rev: string = 'REV-01', sheetTitle?: string): string {
  const payload = {
    app: 'Fiza Hayat Architects & BIM Studio',
    projectId: project.id,
    slug: project.slug,
    title: project.title,
    sheetNumber: sheet,
    sheetTitle: sheetTitle || 'ARCHITECTURAL WORKING DRAWING',
    revision: rev,
    client: project.clientName,
    location: project.location || 'Global',
    bimLevel: project.bimLevel || 'LOD 400',
    url: typeof window !== 'undefined' ? `${window.location.origin}/?project=${project.id}&sheet=${encodeURIComponent(sheet)}&rev=${encodeURIComponent(rev)}` : `https://fizahayat.com/?project=${project.id}`
  };
  return JSON.stringify(payload);
}

/**
 * Plays a pleasant high-tech audio chime when blueprint is detected.
 */
export function playBlueprintBeepSound() {
  try {
    const AudioContextClass = window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext;
    if (!AudioContextClass) return;
    const ctx = new AudioContextClass();
    
    // First tone
    const osc1 = ctx.createOscillator();
    const gain1 = ctx.createGain();
    osc1.type = 'sine';
    osc1.frequency.setValueAtTime(880, ctx.currentTime); // A5
    gain1.gain.setValueAtTime(0.15, ctx.currentTime);
    gain1.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.12);
    osc1.connect(gain1);
    gain1.connect(ctx.destination);
    osc1.start(ctx.currentTime);
    osc1.stop(ctx.currentTime + 0.12);

    // Second tone (higher confirmation tone)
    const osc2 = ctx.createOscillator();
    const gain2 = ctx.createGain();
    osc2.type = 'sine';
    osc2.frequency.setValueAtTime(1760, ctx.currentTime + 0.1); // A6
    gain2.gain.setValueAtTime(0.2, ctx.currentTime + 0.1);
    gain2.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.28);
    osc2.connect(gain2);
    gain2.connect(ctx.destination);
    osc2.start(ctx.currentTime + 0.1);
    osc2.stop(ctx.currentTime + 0.28);
  } catch {
    // AudioContext blocked by browser autoplay or unsupported
  }
}
